export const colors = {
  'on-error-container': '#ffdad6',
  'on-tertiary-container': '#602a47',
  'on-primary': '#402d00',
  'primary-fixed-dim': '#ebc166',
  'card-back': '#3D0C29',
  'tertiary-fixed-dim': '#fcb0d4',
  'on-secondary': '#451078',
  'surface-variant': '#383241',
  'inverse-on-surface': '#332e3d',
  'secondary-fixed': '#efdbff',
  'outline-variant': '#4e4637',
  'on-error': '#690005',
  'on-secondary-container': '#cea2ff',
  tertiary: '#fcb0d4',
  'secondary-container': '#5c2d90',
  'glow-violet': '#2A1B3D',
  secondary: '#dab8ff',
  'on-secondary-fixed-variant': '#5c2d90',
  'tertiary-fixed': '#ffd8e8',
  'surface-container-low': '#1e1927',
  'on-primary-fixed': '#261a00',
  primary: '#ebc166',
  error: '#ffb4ab',
  background: '#16111f',
  'on-tertiary-fixed': '#380725',
  'surface-container-highest': '#383241',
  'primary-fixed': '#ffdf9e',
  'surface-container-high': '#2d2836',
  'on-primary-container': '#4f3900',
  'background-void': '#0B0714',
  'inverse-surface': '#e8dff3',
  surface: '#16111f',
  'on-surface': '#e8dff3',
  'on-primary-fixed-variant': '#5b4300',
  'on-surface-variant': '#d1c5b2',
  'tertiary-container': '#da92b4',
  'on-tertiary': '#521e3a',
  'surface-tint': '#ebc166',
  'inverse-primary': '#795902',
  'primary-container': '#c9a24b',
  'on-secondary-fixed': '#2b0053',
  'on-background': '#e8dff3',
  'accent-magenta': '#7B4397',
  'highlight-lavender': '#E8DFFF',
  'surface-dim': '#16111f',
  'surface-container-lowest': '#100c19',
  'surface-container': '#221d2c',
  'surface-bright': '#3c3746',
  'background-nebula': '#120C1F',
  'error-container': '#93000a',
  outline: '#9a8f7e',
  'on-tertiary-fixed-variant': '#6c3451',
  'secondary-fixed-dim': '#dab8ff',
} as const

export const borderRadius = {
  DEFAULT: '0.25rem',
  lg: '0.5rem',
  xl: '0.75rem',
  full: '9999px',
} as const

export const spacing = {
  'margin-mobile': '16px',
  'container-max': '1200px',
  'stack-md': '16px',
  'stack-sm': '8px',
  'stack-lg': '32px',
  gutter: '24px',
  'section-padding': '80px',
} as const

export const fontFamily = {
  'display-lg-mobile': ['Cinzel'],
  'tagline-italic': ['Playfair Display'],
  'display-lg': ['Cinzel'],
  'display-md': ['Cinzel'],
  'body-md': ['Inter'],
  'label-caps': ['Cinzel'],
  'body-lg': ['Inter'],
} as const

export const fontSize = {
  'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
  'tagline-italic': ['20px', { lineHeight: '1.5', fontWeight: '400' }],
  'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
  'display-md': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
  'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
  'label-caps': ['14px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
  'body-lg': ['18px', { lineHeight: '1.8', fontWeight: '400' }],
} as const
